const set = new Set()

.add(require('../../commands/Admin/embed'))
.add(require('../../commands/Admin/poll'))
.add(require('../../commands/Admin/prefix'))
.add(require('../../commands/Admin/resetSettings'))
.add(require('../../commands/Admin/setCommandsChannel'))
.add(require('../../commands/Admin/setRank'))
.add(require('../../commands/Admin/setWelcomeChannel'))
.add(require('../../commands/Admin/unsetRank'))
.add(require('../../commands/Dev/backup'))
.add(require('../../commands/Dev/eval'))
.add(require('../../commands/Fun/8ball'))
.add(require('../../commands/Fun/coinflip'))
.add(require('../../commands/Fun/roll'))
.add(require('../../commands/Fun/rps'))
.add(require('../../commands/Moderation/ban'))
.add(require('../../commands/Moderation/clearwarnings'))
.add(require('../../commands/Moderation/kick'))
.add(require('../../commands/Moderation/lock'))
.add(require('../../commands/Moderation/mute'))
.add(require('../../commands/Moderation/purge'))
.add(require('../../commands/Moderation/removewarn'))
.add(require('../../commands/Moderation/softban'))
.add(require('../../commands/Moderation/unban'))
.add(require('../../commands/Moderation/unlock'))
.add(require('../../commands/Moderation/unmute'))
.add(require('../../commands/Moderation/warn'))
.add(require('../../commands/Moderation/warnings'))
.add(require('../../commands/Utility/avatar'))
.add(require('../../commands/Utility/help'))
.add(require('../../commands/Utility/invite'))
.add(require('../../commands/Utility/level'))
.add(require('../../commands/Utility/ping'))
.add(require('../../commands/Utility/ranks'))
.add(require('../../commands/Utility/top'))

;module.exports = set;